### PR TITLE
#4 postgres_data_dir in a variable

### LINKED ISSUE #4: Make postgres_data_dir configurable via variable
The default AWX install configuration sets `postgres_data_dir` as /tmp/pgdocker, which is a bit annoying if you want to keep a persistant installation and try AWX for a few days (weeks, months) time. It is easy to change it if you install it from scratch, but not with this role.

### PR DESCRIPTION
**Pull request by jnogol**
Fixes #4. Modified Run the AWX installation playbook task. Added postgres_data_dir in defaults/main.yml

### CODE REVIEW

**Comment by tmor** [comment]
`/tmp` will be deleted in 10 days for RHEL/CentOS .
so, I suggest `/var/lib/pgdocker` .

**Comment by rndmh3ro** [comment]
Setting this to `/var/lib/pgdocker` is indeed the better alternative.
Aside from this the PR works for me.

**Comment by jnogol** [comment]
Done. Now let's see if @geerlingguy is ok with it

**Comment by vab2048** [comment]
Can this please be merged?
It would make life a lot easier for those who use this role.

**Comment by jnogol** [comment]
I wouldn't expect that any soon, based on how much attention he's paying on this repo

**Comment by rndmh3ro** [comment]
FWIW I forked the role here: https://github.com/rndmh3ro/ansible-role-awx
I merged all the PRs from this role in my own role, especially this one here and intend to provide more support. I released a version 2.0.0 that contains this PR.

**Comment by geerlingguy** [comment]
This looks helpful, and will solve probably the #1 surprising complaint when installing AWX from the role (that is... the database going AWOL). Thanks!

**Pull request merged**
