### PR TITLE
Specify awx installation vars

### PR DESCRIPTION
**Pull request by senorsmile**
This commit forces values for postgres_data_dir and awx_secret_key so that they can be overridden.

Sane defaults are provided.

README updated.

### CODE REVIEW

**Comment by senorsmile** [comment]
Not sure, but this may address some of what is meant on:  https://github.com/geerlingguy/ansible-role-awx/issues/2

**Comment by senorsmile** [comment]
Just discovered that this is not passing the postgres_data_dir correctly.  marking donotmerge until local testing shows things working.

**Comment by senorsmile** [comment]
Review test was using the wrong branch (master instead of this branch).  Retesting and confirmed that it is picking up the new parameters.   All ready for review.

**Comment by geerlingguy** [comment]
Looks good at first glance, and passes tests.

**Comment by geerlingguy** [comment]
Note that the `postgres_data_dir` was already merged in PR #5 — I'm willing to add in `awx_secret_key` (though it's getting a little unwieldy having all these vars passed one by one; maybe we can print a list or something using Jinja formatting?).

**Pull request closed without merging**
